version: '2.1'
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: 'cimg/buildpack-deps:stretch'
    environment:
      IMAGE_NAME: nginx
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t nginx .
      - snyk/scan:
          docker-image-name: nginx
workflows: null
